### PR TITLE
Feature/travis

### PR DESCRIPTION
**Pull request by HiromuHota**

### CODE REVIEW

**Comment by HiromuHota** [comment]
Even now, you can see the travis runs at https://travis-ci.com/HiromuHota/fonduer-tutorials.

**Comment by senwu** [comment]
We had the same issue here: https://github.com/HazyResearch/fonduer/pull/75

**Comment by HiromuHota** [comment]
@SenWu Exactly the same error message.
> WandError: wand contains no images `MagickWand-3' @ error/magick-image.c/MagickGetImageFormat/5158

Let's see what I do.

**Comment by HiromuHota** [comment]
Superseded by #74. Close.

**Pull request closed without merging**
