### PR TITLE
Update tutorials for v0.2.3 and add intro tutorials

### PR DESCRIPTION
**Pull request by lukehsiao**
Now that Fonduer v0.2.3 has been release on PyPI, this updates the tutorials to showcase the updated APIs.

### CODE REVIEW

**Comment by samhavens** [comment]
Hi, this is probably user error, but I can't get the database creation/filling to work:

```sh
➜  fonduer-tutorials git:(tutorials) ✗ cd intro
➜  intro git:(tutorials) ✗ ./download_data.sh
Downloading tutorial databases...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2242k  100 2242k    0     0   365k      0  0:00:06  0:00:06 --:--:--  623k
Unpacking hardware tutorial data...
x intro_data_model.sql
x intro_candidates.sql
x intro_supervision.sql
Deleting tar file...
Done!
➜  intro git:(tutorials) ✗ createdb intro_data_model
➜  intro git:(tutorials) ✗ psql intro_data_model < data/intro_data_model.sql > /dev/null
ERROR:  syntax error at or near "AS"
LINE 2:     AS integer
            ^
ERROR:  relation "public.candidate_id_seq" does not exist
ERROR:  syntax error at or near "AS"
LINE 2:     AS integer
            ^
ERROR:  relation "public.context_id_seq" does not exist
ERROR:  syntax error at or near "AS"
LINE 2:     AS integer
            ^
ERROR:  relation "public.feature_key_id_seq" does not exist
ERROR:  syntax error at or near "AS"
LINE 2:     AS integer
            ^
ERROR:  relation "public.gold_label_key_id_seq" does not exist
ERROR:  syntax error at or near "AS"
LINE 2:     AS integer
            ^
ERROR:  relation "public.label_key_id_seq" does not exist
ERROR:  syntax error at or near "AS"
LINE 2:     AS integer
            ^
ERROR:  relation "public.marginal_id_seq" does not exist
ERROR:  syntax error at or near "AS"
LINE 2:     AS integer
            ^
ERROR:  relation "public.prediction_key_id_seq" does not exist
ERROR:  relation "public.candidate_id_seq" does not exist
ERROR:  relation "public.context_id_seq" does not exist
ERROR:  relation "public.feature_key_id_seq" does not exist
ERROR:  relation "public.gold_label_key_id_seq" does not exist
ERROR:  relation "public.label_key_id_seq" does not exist
ERROR:  relation "public.marginal_id_seq" does not exist
ERROR:  relation "public.prediction_key_id_seq" does not exist
ERROR:  relation "public.candidate_id_seq" does not exist
LINE 1: SELECT pg_catalog.setval('public.candidate_id_seq', 1, false...
                                 ^
ERROR:  relation "public.context_id_seq" does not exist
LINE 1: SELECT pg_catalog.setval('public.context_id_seq', 16181, tru...
                                 ^
ERROR:  relation "public.feature_key_id_seq" does not exist
LINE 1: SELECT pg_catalog.setval('public.feature_key_id_seq', 1, fal...
                                 ^
ERROR:  relation "public.gold_label_key_id_seq" does not exist
LINE 1: SELECT pg_catalog.setval('public.gold_label_key_id_seq', 1, ...
                                 ^
ERROR:  relation "public.label_key_id_seq" does not exist
LINE 1: SELECT pg_catalog.setval('public.label_key_id_seq', 1, false...
                                 ^
ERROR:  relation "public.marginal_id_seq" does not exist
LINE 1: SELECT pg_catalog.setval('public.marginal_id_seq', 1, false)...
                                 ^
ERROR:  relation "public.prediction_key_id_seq" does not exist
LINE 1: SELECT pg_catalog.setval('public.prediction_key_id_seq', 1, ...
```

**Comment by senwu** [comment]
@samhavens 
Thanks for your information!
Which version of PostgreSQL are you using? Fonduer requires PostgreSQL version 9.6 or above.

**Comment by samhavens** [comment]
@SenWu 9.6.1.0

**Comment by senwu** [comment]
@samhavens Sorry about the issue. We were using 10.4 to generate those databases. All databases are updated (you can redownload them) and the notebook logs as well. Please let us know you still have issues. Thanks.

**Pull request merged**
