### PR TITLE
Add GitHub Actions

### PR DESCRIPTION
**Pull request by HiromuHota**
This supersedes #59.

This action checks if notebooks run without error.

### CODE REVIEW

**Comment by HiromuHota** [comment]
The job takes about 35 mins to finish.

**Comment by HiromuHota** [comment]
If you are interested, please take a look at this PR in action: https://github.com/HiromuHota/fonduer-tutorials/actions

**Comment by senwu** [comment]
This is awesome! Thanks!

I have one question here about the setting.
Should we the virtual env and install Fonduer from the requirement instead of the docker image here? Since the docker image might not match requirement in the repo (for example: for PR which require a new version of Fonduer).

**Comment by HiromuHota** [comment]
@SenWu Good question. I think the answer depends on the update cycle of Fonduer, its Docker image, and the tutorials.

The current update cycle is as follows:
1. A new version of Fonduer is released.
2. Then, the Docker image is updated and released.
3. Finally, the tutorials get updated.

As long as this update cycle is in place, the current PR works and the notebooks will be tested against the updated version of Fonduer because the Docker image `hiromuhota/fonduer` (this is an alias of `hiromuhota/fonduer:latest`) will be updated by the time we start working on step 3.

An alternative update cycle would be:
1. The tutorials get updated so that they work with a new version of Fonduer before its release.
2. A new version of Fonduer is released.
3. Then, the Docker image is updated and released.

If we switch to this cycle, it'd be good to use requirements.txt and a PR (for the 1st step in the alternative cycle) would install the latest commit of Fonduer like below:
```
git+git://github.com/HazyResearch/fonduer.git@master
jupyter
matplotlib
```

IMO, the current update cycle is good enough and the alternative approach overlaps the unit tests of Fonduer.
If a tutorial does not work with a new released version of Fonduer, this means that the unit tests of Fonduer do not cover a general use of Fonduer and they should be improved.
The workflow of this PR is to automate a part of checks during notebooks update by offloading it to GitHub Actions.

I think I'm telling a lot beyond what you pointed out, but please let me know if there is anything I overlook.

**Review by lukehsiao — COMMENTED** [review]
This LGTM

**Pull request merged**
